"""migração inicial

Revision ID: 41f17524866b
Revises: 
Create Date: 2026-04-08 08:11:54.318423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f17524866b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('função', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PRONTO', 'EM_USO', 'QUEBRADO', 'IRREGULAR', 'MANUTENCAO', name='status_veiculo_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Motorista-veiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('motorist_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['motorist_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutenções',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('oficina_responsavel', sa.String(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manutenções')
    op.drop_table('Motorista-veiculo')
    op.drop_table('Documentos')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
